package com.ssmbase.basesic.dao;

import com.ssmbase.basesic.model.WxMenu;

import java.util.List;

public interface WxMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Wx_Button_Menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Wx_Button_Menu
     *
     * @mbg.generated
     */
    int insert(WxMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Wx_Button_Menu
     *
     * @mbg.generated
     */
    int insertSelective(WxMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Wx_Button_Menu
     *
     * @mbg.generated
     */
    WxMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Wx_Button_Menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WxMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Wx_Button_Menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WxMenu record);

    /**
     * 根据ParentId查询菜单
     */
    List<WxMenu> queryWxMenu(WxMenu wxMenu);
}