package com.ssmbase.basesic.model;

import javax.persistence.Id;
import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.id
     *
     * @mbg.generated
     */
    @Id
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.UserName
     *
     * @mbg.generated
     */

    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.LoginName
     *
     * @mbg.generated
     */
    private String loginname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Sex
     *
     * @mbg.generated
     */
    private Boolean sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.CreateTimeDate
     *
     * @mbg.generated
     */
    private Date createtimedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.CreateUserId
     *
     * @mbg.generated
     */
    private Integer createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.UpdateTimeDate
     *
     * @mbg.generated
     */
    private Date updatetimedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.UpdateUserId
     *
     * @mbg.generated
     */
    private Integer updateuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table User
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated
     */
    public User(Integer id, String username, String password, String loginname, Boolean sex, Date createtimedate, Integer createuserid, Date updatetimedate, Integer updateuserid) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.loginname = loginname;
        this.sex = sex;
        this.createtimedate = createtimedate;
        this.createuserid = createuserid;
        this.updatetimedate = updatetimedate;
        this.updateuserid = updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.id
     *
     * @return the value of User.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.id
     *
     * @param id the value for User.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.UserName
     *
     * @return the value of User.UserName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.UserName
     *
     * @param username the value for User.UserName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Password
     *
     * @return the value of User.Password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Password
     *
     * @param password the value for User.Password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.LoginName
     *
     * @return the value of User.LoginName
     *
     * @mbg.generated
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.LoginName
     *
     * @param loginname the value for User.LoginName
     *
     * @mbg.generated
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Sex
     *
     * @return the value of User.Sex
     *
     * @mbg.generated
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Sex
     *
     * @param sex the value for User.Sex
     *
     * @mbg.generated
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.CreateTimeDate
     *
     * @return the value of User.CreateTimeDate
     *
     * @mbg.generated
     */
    public Date getCreatetimedate() {
        return createtimedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.CreateTimeDate
     *
     * @param createtimedate the value for User.CreateTimeDate
     *
     * @mbg.generated
     */
    public void setCreatetimedate(Date createtimedate) {
        this.createtimedate = createtimedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.CreateUserId
     *
     * @return the value of User.CreateUserId
     *
     * @mbg.generated
     */
    public Integer getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.CreateUserId
     *
     * @param createuserid the value for User.CreateUserId
     *
     * @mbg.generated
     */
    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.UpdateTimeDate
     *
     * @return the value of User.UpdateTimeDate
     *
     * @mbg.generated
     */
    public Date getUpdatetimedate() {
        return updatetimedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.UpdateTimeDate
     *
     * @param updatetimedate the value for User.UpdateTimeDate
     *
     * @mbg.generated
     */
    public void setUpdatetimedate(Date updatetimedate) {
        this.updatetimedate = updatetimedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.UpdateUserId
     *
     * @return the value of User.UpdateUserId
     *
     * @mbg.generated
     */
    public Integer getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.UpdateUserId
     *
     * @param updateuserid the value for User.UpdateUserId
     *
     * @mbg.generated
     */
    public void setUpdateuserid(Integer updateuserid) {
        this.updateuserid = updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", loginname=").append(loginname);
        sb.append(", sex=").append(sex);
        sb.append(", createtimedate=").append(createtimedate);
        sb.append(", createuserid=").append(createuserid);
        sb.append(", updatetimedate=").append(updatetimedate);
        sb.append(", updateuserid=").append(updateuserid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}