package com.ssmbase.basesic.model;

import java.io.Serializable;

public class UserInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.Name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.LoginName
     *
     * @mbg.generated
     */
    private String loginname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.PassWord
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.WxId
     *
     * @mbg.generated
     */
    private String wxid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UserInfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserInfo
     *
     * @mbg.generated
     */
    public UserInfo(Integer id, String name, String loginname, String password, String wxid) {
        this.id = id;
        this.name = name;
        this.loginname = loginname;
        this.password = password;
        this.wxid = wxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserInfo
     *
     * @mbg.generated
     */
    public UserInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.Id
     *
     * @return the value of UserInfo.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.Id
     *
     * @param id the value for UserInfo.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.Name
     *
     * @return the value of UserInfo.Name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.Name
     *
     * @param name the value for UserInfo.Name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.LoginName
     *
     * @return the value of UserInfo.LoginName
     *
     * @mbg.generated
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.LoginName
     *
     * @param loginname the value for UserInfo.LoginName
     *
     * @mbg.generated
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.PassWord
     *
     * @return the value of UserInfo.PassWord
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.PassWord
     *
     * @param password the value for UserInfo.PassWord
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.WxId
     *
     * @return the value of UserInfo.WxId
     *
     * @mbg.generated
     */
    public String getWxid() {
        return wxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.WxId
     *
     * @param wxid the value for UserInfo.WxId
     *
     * @mbg.generated
     */
    public void setWxid(String wxid) {
        this.wxid = wxid == null ? null : wxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserInfo
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", loginname=").append(loginname);
        sb.append(", password=").append(password);
        sb.append(", wxid=").append(wxid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}